### ISSUE TITLE
Fonction actualizaPesos non utilisée

### ISSUE THREAD

**Issue by Raul6469** [VictorCadix/Neural_Network_github#17]
``` cpp
void Neurona::actualizaPesos(){
	for (int a=0; a<this->neuronasCapaAnterior; a++){
		this->pesos[a];
	}
}
```
Elle sert à quoi ? Elle n'est appelée nulle part...

**Comment by VictorCadix** [comment]
Elle est appelée nulle part et elle fait rien.
J'avais du commencée a écrire la fonction et.... 
Si tu veux la supprimer, vas-y.
