### ISSUE TITLE
Déterminer critère de sélection

### ISSUE THREAD

**Issue by Raul6469** [VictorCadix/Neural_Network_github#9]
- [x] Calculate the error (PR #26)
- [x] Generate the fitness function (master)
- [x] Selection % best networks (PR #30)

**Comment by VictorCadix** [comment]
_EDIT (par @Raul6469) : cases déplacées en description pour afficher la barre de progression et éviter les doublons_

```
- [ ] Calculate the error
- [ ] Generate the fitness function
- [ ] Selection %
```

**Comment by Raul6469** [comment]
Ce serait possible de préciser les tâches ? Je ne suis pas sûr de tout comprendre 😕

**Comment by VictorCadix** [comment]
Pour la fitness fonction je propose d'utiliser un fonction du type (1-error)², comme ça, celui qui commet l'erreur le plus petit a une meilleure ponctuation.

**Comment by VictorCadix** [comment]
Dans le commit bcc5e84d16aae7b84bd6c9479ce122d61b4db0ba je calcule les points de fitness a partir de (1-error)^3. Plus l'exposent est haut moins de possibilités ont les mauvais réseaux de se reproduire.
![capture](https://user-images.githubusercontent.com/31282394/30905919-85bd6f54-a376-11e7-8e3f-2f3ac68f0539.PNG)

**Comment by VictorCadix** [comment]
Les 5 derniers commits je les ai fait directement sur master. 
- bcc5e84d16aae7b84bd6c9479ce122d61b4db0ba
- 916f1a2877baa4fe08a649af93dab6169f3cff5a
- eb488ff8f1dcc77b931bff8daa4e0495b75c20c0
- 64f4ed1d29b5571a6db095060d49dd4b3b355e40
- 844d67ace1a5c4caa4fde470281c9951891b8b1a

Je fais cette liste pour que ça soit plus facile les retrouver et savoir a qu'elle partie ils appartient. 
Pour la sélection% je ouvre une branche.

**Comment by VictorCadix** [comment]
Branche de la sélection% -> #29 
Par contre je ne comprend pas ou est le problème avec Appveyor 😞 
https://ci.appveyor.com/project/VictorCadix/neural-network-github/build/1.0.275

**Comment by Raul6469** [comment]
Le problème d'AppVeyor c'est le nom de la branche : de manière générale, il ne faut jamais utiliser de caractères spéciaux en informatique, certains peuvent être mal interprétés. Du coup j'ai supprimé la branche `Selection%` en `Selection`, et remis tous tes commits dans la nouvelle branche. #29 est donc fermée et #30 prend le relais.

Et sinon c'est pratiquement _jamais_ une bonne idée de travailler directement sur master, il vaut toujours mieux passer par une branche pour éviter les problèmes... Utiliser une branche aurait permis de ne pas avoir à lister les commits concernés, il aurait suffi de mentionner cette issue dans la PR.
